version: '3.8'

services:
    dev:
        container_name: nest-api-dev
        image: nest-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:dev
        ports:
            - 3000:3000
            - 9487:9487
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: always
    
networks:
    nesjs-network: